---
AWSTemplateFormatVersion: '2010-09-09'
Description: Cloud9 + QuickStart VPC (qs-1pb4pod81) (Please do not remove) May,29,2019
Metadata:
  LICENSE: Apache License, Version 2.0 
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: VPC network configuration
      Parameters:
      - NumberOfAZs    
      - PrivateSubnet1CIDR
      - PublicSubnet1CIDR
    - Label:
        default: Bastion configuration
      Parameters:
      - RemoteAccessCIDR
    - Label:
        default: Cloud9 configuration
      Parameters:
      - C9InstanceType
      - C9StopTime
      - EBSVolumeSize    
    - Label:
        default: AWS Quick Start configuration
      Parameters:     
      - QSS3BucketName
      - QSS3KeyPrefix          
    ParameterLabels:
      QSS3BucketName:
        default: Quick Start S3 bucket name
      QSS3KeyPrefix:
        default: Quick Start S3 key prefix    
      EBSVolumeSize:
        default: EBS volume size
      C9InstanceType:
        default: Cloud9 instance type
      C9StopTime:
        default: Stop time
      NumberOfAZs:
        default: Number of Availability Zones          
      PrivateSubnet1CIDR:
        default: Private subnet 1 CIDR
      PublicSubnet1CIDR:
        default: Public subnet 1 CIDR
      RemoteAccessCIDR:
        default: Allowed external access CIDR
Parameters:
  QSS3BucketName:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: Quick Start bucket name can include numbers, lowercase
      letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen
      (-).
    Default: "aws-jam-challenge-resources"
    Description: S3 bucket name for the Quick Start assets. This string can include
      numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start
      or end with a hyphen (-).
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: ^[0-9a-zA-Z-/.]*$
    ConstraintDescription: Quick Start key prefix can include numbers, lowercase letters,
      uppercase letters, hyphens (-), dots(.) and forward slash (/).
    Default: "Cognito-Fine-Grained-Auth-External-IdP"
    Description: S3 key prefix for the Quick Start assets. Quick Start key prefix
      can include numbers, lowercase letters, uppercase letters, hyphens (-), dots(.) and
      forward slash (/).
    Type: String
  RemoteAccessCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(3[0-2]|[1-2][0-9]|[0-9]))$|(^Auto$)
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/x
    Description: The CIDR IP range that is permitted to access the AWS Cloud9 desktop. We recommend that you set this value to a trusted
      IP range. Alternatively, keep the default "Auto" setting to provide access to only the IP address launching the stack.
    Type: String
    Default: '169.254.0.1/32'
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instances.
    Default: "cognito-ext-idp"
  AvailabilityZones:
    Description: >-
      List of Availability Zones to use for the subnets in the VPC. Only two
      Availability Zones are used for this deployment, and the logical order of
      your selections is preserved. 
    Default: "us-west-2a,us-west-2b"
    Type: CommaDelimitedList
  PrivateSubnet1CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.0.0/19
    Description: CIDR block for private subnet 1 located in Availability Zone 1.
    Type: String
  PublicSubnet1CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.128.0/20
    Description: CIDR block for the public (DMZ) subnet 1 located in Availability
      Zone 1.
    Type: String
  C9InstanceType:
    Description: The instance type of the new Amazon EC2 instance that AWS Cloud9
      will launch for the development environment.
    Type: String
    Default: t2.medium
    AllowedValues:
    - t2.small
    - t2.medium
    - t2.large
    - t2.xlarge
    - t2.2xlarge
    - t3.nano
    - t3.micro
    - t3.small
    - t3.medium
    - t3.large
    - t3.xlarge
    - t3.2xlarge
  C9StopTime:
    Description: The number of minutes until the running instance is shut down after
      the environment has last been used.
    Type: Number
    Default: 30
  EBSVolumeSize:
    Description: The desired size (in GB) of the Amazon EBS volume for your Cloud9 IDE.
    Type: Number
    Default: 50
  NumberOfAZs:
    Description: Number of Availability Zones to use in the VPC. This must match your selections in the list of Availability Zones parameter.
    Type: String
    Default: 2
    AllowedValues:
    - 2   
Conditions:
  AutoCIDR: !Equals
    - !Ref RemoteAccessCIDR
    - 'Auto'   
Resources: 
              
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}/aws-vpc.template'
      Parameters:
        AvailabilityZones: !Join 
          - ','
          - !Ref AvailabilityZones
        CreatePrivateSubnets: 'true'
        KeyPairName: !Ref KeyName
        PrivateSubnet1ACIDR: !Ref PrivateSubnet1CIDR
        PublicSubnet1CIDR: !Ref PublicSubnet1CIDR
        NumberOfAZs: !Ref NumberOfAZs       
  IDEStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}/cloud9-ide-instance.yaml'    
      Parameters:
        EBSVolumeSize: !Ref EBSVolumeSize
        C9InstanceType: !Ref C9InstanceType
        C9StopTime: !Ref 'C9StopTime'
        C9Subnet: !GetAtt 'VPCStack.Outputs.PublicSubnet1ID'
        QSS3BucketName: !Sub ${QSS3BucketName}
        QSS3KeyPrefix: !Ref QSS3KeyPrefix
  
  